### ISSUE TITLE
travis test fails

### ISSUE THREAD

**Issue by nathanlyons** [landlab/tutorials#20]
Some test are failing for #18. The error looks like: ```python[version='>=3.6,<3.7.0a0']```.

@mcflugen, is this a similar issue that was resolved in https://github.com/landlab/landlab/pull/633?

**Comment by mcflugen** [comment]
@nathanlyons Yes, I'm pretty sure.

landlab needs to be installed into an environment and the tests run in that environment.

So `.travis.ym` should have something like
```
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
```
instead of
```
- conda install python=$TRAVIS_PYTHON_VERSION
```
The problem is that the latest version of miniconda installs Python 3 into the root environment, which means that if we want to install a different version of Python, we have to install it into a separate environment (this used to not be the case).

**Comment by nathanlyons** [comment]
@mcflugen Thanks. Do you think #21 might address this issue? The issue and yml of this pull are congruent.
