### ISSUE TITLE
Travis test fails

### ISSUE THREAD

**Issue by gregtucker** [landlab/tutorials#52]
The travis tests seem to be generating

ImportError: no module named landlab

@mcflugen any ideas?

**Comment by mcflugen** [comment]
@gregtucker The problem is that *landlab* is not being installed correctly when not on the *release* branch. When running the tests on *release*, *landlab* is installed with `conda install landlab`. However, when on another branch, landlab is cloned and installed from source (you can see this in [`.travis.yaml`](https://github.com/landlab/tutorials/blob/07f4d7d4765fbd559c4c9ca1540371b5da61bc6e/.travis.yml#L37)). This is whey the PR passes (it's being merged into *release*) but the push doesn't.

I'll have to have a look at this tomorrow to see what the best way to fix this is.

**Comment by gregtucker** [comment]
@mcflugen Can safely ignore it then, since the pr gets tested properly?

**Comment by kbarnhart** [comment]
@gregtucker @mcflugen I fixed this in #67
